---
ID: "8683fcff-4e75-4f21-beaa-0d8e7aa0beaa"
Parent: "a921362b-43ce-4ecc-afe3-0c8d0320ae81"
Template: "2e1d7985-0bf1-469b-a00b-4f2ac443940c"
Path: /sitecore/content/SXA Reference/Playground/pl/Presentation/Rendering Variants/JSON Results/Default
DB: master
BranchID: "692e3473-3749-464c-845d-8d515419a63d"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170523T154222Z
