---
ID: "9dcdc937-baff-483d-aeb9-30aafc6ca3cd"
Parent: "dbf95b59-47d0-4b49-b686-1a6b72cd67a6"
Template: "dbf95b59-47d0-4b49-b686-1a6b72cd67a6"
Path: /sitecore/templates/Project/SXA Reference/Playground/Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170212T133318Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\Admin
